// Button.jsx
// Using a CSS Module. We import the styles object and read class names from it.

import styles from "./Button.module.css";

function Button() {
  // styles.button is a unique class name generated by the build tool.
  return <button className={styles.button}>Save</button>;
}

export default Button;
